version: "3.9"

services:
  flask:
    container_name: flask_app
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    env_file:
      - ./test.env
    ports:
      - 5000:5000
