version: "3.9"

services:
  flask_pre:
    container_name: flask_app_pre
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    env_file:
      - ./test.env
    ports:
      - 5555:5000
    networks:
      - net_app_pre
  db_host_pre:
    container_name: db_app_pre
    image: mysql/mysql-server:5.7
    env_file:
      - ./test.env
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
    volumes:
      - app_data_pre:/var/lib/mysql
    networks:
      - net_app_pre

volumes:
  app_data_pre:

networks:
  net_app_pre:
