#####
# Hostname:
#####
hostname_server: sauron


#####
# List of apt packages to install:
#####
list_additional_pkg:
  - git-all
  - nginx


#####
# Vhosts:
#####
# Paths ansible conf:
src_vhosts_path: /var/jenkins_home/ansible/conf/sauron/vhosts

# Paths in host:
dest_vhosts_available_path: /etc/nginx/sites-available
dest_vhosts_enabled_path: /etc/nginx/sites-enabled

symbolic_link_vhost:
  - ci_helmcode_com.conf
