---
- name: Change script deploy permissions
  ansible.builtin.file:
    path: /var/www/helmcode.com/scripts/deploy.sh
    owner: root
    group: root
    mode: '0744'

- name: Run a deploy script
  command: sh /var/www/helmcode.com/scripts/deploy.sh
