---
- name: Install software whit apt
  apt:
    update_cache: yes
    state: latest
    pkg:
    - fail2ban
    - nginx
    - python3-pip
    - git-all
    - mysql-server
    - certbot
    - python3-certbot-nginx
    - apache2-utils
