---
- name: Install comun software whit apt
  apt:
    update_cache: yes
    state: latest
    pkg:
    - fail2ban
    - htop
    - python3-pip

- name: Install additional software whit apt
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items: "{{ list_additional_pkg }}"
  when: list_additional_pkg is defined
